version: '3.7'

services:

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .envs/dev/django
      - .envs/dev/postgres
    depends_on:
      - postgres
      - mailhog

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/dev/postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8026:8025"

volumes:
  postgres_data: