# Generated by Django 3.0.5 on 2022-11-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_in_file',
            field=models.CharField(max_length=10),
        ),
    ]
